import { BotB } from "../types/bible";

export const booksOfBible: Array<BotB> = [
  { id: 1, name: "Genesis", abbrev: "GEN" },
  { id: 2, name: "Exodus", abbrev: "EXO" },
  { id: 3, name: "Leviticus", abbrev: "LEV" },
  { id: 4, name: "Numbers", abbrev: "NUM" },
  { id: 5, name: "Deuteronomy", abbrev: "DEU" },
  { id: 6, name: "Joshua", abbrev: "JOS" },
  { id: 7, name: "Judges", abbrev: "JDG" },
  { id: 8, name: "Ruth", abbrev: "RUT" },
  { id: 9, name: "1 Samuel", abbrev: "1SA" },
  { id: 10, name: "2 Samuel", abbrev: "2SA" },
  { id: 11, name: "1 Kings", abbrev: "1KI" },
  { id: 12, name: "2 Kings", abbrev: "2KI" },
  { id: 13, name: "1 Chronicles", abbrev: "1CH" },
  { id: 14, name: "2 Chronicles", abbrev: "2CH" },
  { id: 15, name: "Ezra", abbrev: "EZR" },
  { id: 16, name: "Nehemiah", abbrev: "NEH" },
  { id: 17, name: "Esther", abbrev: "EST" },
  { id: 18, name: "Job", abbrev: "JOB" },
  { id: 19, name: "Psalms", abbrev: "PSA" },
  { id: 20, name: "Proverbs", abbrev: "PRO" },
  { id: 21, name: "Ecclesiastes", abbrev: "ECC" },
  { id: 22, name: "Song of Solomon", abbrev: "SNG" },
  { id: 23, name: "Isaiah", abbrev: "ISA" },
  { id: 24, name: "Jeremiah", abbrev: "JER" },
  { id: 25, name: "Lamentations", abbrev: "LAM" },
  { id: 26, name: "Ezekiel", abbrev: "EZK" },
  { id: 27, name: "Daniel", abbrev: "DAN" },
  { id: 28, name: "Hosea", abbrev: "HOS" },
  { id: 29, name: "Joel", abbrev: "JOL" },
  { id: 30, name: "Amos", abbrev: "AMO" },
  { id: 31, name: "Obadiah", abbrev: "OBA" },
  { id: 32, name: "Jonah", abbrev: "JON" },
  { id: 33, name: "Micah", abbrev: "MIC" },
  { id: 34, name: "Nahum", abbrev: "NAM" },
  { id: 35, name: "Habakkuk", abbrev: "HAB" },
  { id: 36, name: "Zephaniah", abbrev: "ZEP" },
  { id: 37, name: "Haggai", abbrev: "HAG" },
  { id: 38, name: "Zechariah", abbrev: "ZEC" },
  { id: 39, name: "Malachi", abbrev: "MAL" },
  { id: 40, name: "Matthew", abbrev: "MAT" },
  { id: 41, name: "Mark", abbrev: "MRK" },
  { id: 42, name: "Luke", abbrev: "LUK" },
  { id: 43, name: "John", abbrev: "JHN" },
  { id: 44, name: "Acts", abbrev: "ACT" },
  { id: 45, name: "Romans", abbrev: "ROM" },
  { id: 46, name: "1 Corinthians", abbrev: "1CO" },
  { id: 47, name: "2 Corinthians", abbrev: "2CO" },
  { id: 48, name: "Galatians", abbrev: "GAL" },
  { id: 49, name: "Ephesians", abbrev: "EPH" },
  { id: 50, name: "Philippians", abbrev: "PHP" },
  { id: 51, name: "Colossians", abbrev: "COL" },
  { id: 52, name: "1 Thessalonians", abbrev: "1TH" },
  { id: 53, name: "2 Thessalonians", abbrev: "2TH" },
  { id: 54, name: "1 Timothy", abbrev: "1TI" },
  { id: 55, name: "2 Timothy", abbrev: "2TI" },
  { id: 56, name: "Titus", abbrev: "TIT" },
  { id: 57, name: "Philemon", abbrev: "PHM" },
  { id: 58, name: "Hebrews", abbrev: "HEB" },
  { id: 59, name: "James", abbrev: "JAS" },
  { id: 60, name: "1 Peter", abbrev: "1PE" },
  { id: 61, name: "2 Peter", abbrev: "2PE" },
  { id: 62, name: "1 John", abbrev: "1JN" },
  { id: 63, name: "2 John", abbrev: "2JN" },
  { id: 64, name: "3 John", abbrev: "3JN" },
  { id: 65, name: "Jude", abbrev: "JUD" },
  { id: 66, name: "Revelation", abbrev: "REV" },
];
