name: Deploy Migrations to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Check SUPABASE_PROJECT_ID Environment Variable
        run: |
          if [ -z "$SUPABASE_PROJECT_ID" ]; then
            echo "SUPABASE_PROJECT_ID is empty"
          else
            echo "SUPABASE_PROJECT_ID is set"
          fi

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push